# Copyright 2022 Undistro Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if not .Values.ingress.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zora.fullname" . }}-nginx
  labels:
    {{- include "zora.nginxLabels" . | nindent 4 }}
data:
  nginx.conf: |+
    worker_processes  auto;
    pid               /tmp/nginx.pid;

    events {
      worker_connections  3096;
      use                 epoll;
      multi_accept        on;
    }

    http {
      client_body_temp_path   /tmp/client_body_temp;
      proxy_temp_path         /tmp/proxy_temp;
      fastcgi_temp_path       /tmp/fastcgi_temp;
      uwsgi_temp_path         /tmp/uwsgi_temp;
      scgi_temp_path          /tmp/scgi_temp;
      tcp_nodelay             on;

      # this is necessary for us to be able to disable request buffering in all cases
      proxy_http_version 1.1;

      {{- if .Values.ui.enabled }}
      upstream ui {
        server "{{ include "zora.fullname" . }}-ui:{{ .Values.ui.service.port }}";
      }
      {{- end }}

      {{- if .Values.server.enabled }}
      upstream server {
        server "{{ include "zora.fullname" . }}-server:{{ .Values.server.service.port }}";
      }
      {{- end }}

      log_format timed_combined '[$time_local]:$remote_addr - '
        '"$request" $status $body_bytes_sent '
        '"$http_referer" "$http_user_agent" '
        '$request_time $upstream_response_time $pipe';

      access_log /dev/stdout timed_combined;

      map $http_x_forwarded_proto $x_forwarded_proto {
        default $http_x_forwarded_proto;
        ""      $scheme;
      }

      server {
        listen          8080;
        server_tokens   off;
        # disable any limits to avoid HTTP 413 for large image uploads
        client_max_body_size 0;

        # Add extra headers
        add_header X-Frame-Options DENY;
        add_header Content-Security-Policy "frame-ancestors 'none'";

        {{- if .Values.ui.enabled }}
        location / {
          proxy_pass http://ui/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $x_forwarded_proto;
          proxy_buffering off;
          proxy_request_buffering off;
        }
        {{- end }}

        {{- if .Values.server.enabled }}
        location /api/ {
          proxy_pass http://server/api/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $x_forwarded_proto;
          proxy_buffering off;
          proxy_request_buffering off;
        }
        {{- end }}

      }

    }
{{- end }}
