# Copyright 2022 Undistro Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

site_name: "Zora OSS"
site_url: https://zora-docs.undistro.io
repo_url: https://github.com/undistro/zora
repo_name: undistro/zora
edit_uri: edit/main/docs/
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  language: en
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  custom_dir: docs/overrides
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.footer
plugins:
  - search
  - mike:
      version_selector: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/undistrocommunity/shared_invite/zt-21slyrao4-dTW_XtOB90QVj05txOX6rA
    - icon: fontawesome/brands/github
      link: https://github.com/undistro/zora
  analytics:
    provider: google
    property: G-D6NENTNM1P

copyright: Copyright &copy; 2022 - 2023 Undistro Authors

nav:
  - Documentation:
      - "üöÄ Getting Started":
          - Overview: index.md
          - Installation: getting-started/installation.md
      - "üõ†Ô∏è Configuration":
          - Scan schedule: configuration/scan-schedule.md
          - Custom checks with CEL: configuration/custom-checks.md
          - Compute resources: configuration/resources.md
          - Suspending scans: configuration/suspend-scan.md
          - Retain issues: configuration/retain-issues.md
          - HTTPS proxy: configuration/https-proxy.md
          - Ignore unfixed vulnerabilities: plugins/trivy/#large-vulnerability-reports
          - Vulnerability scan timeout: plugins/trivy/#scan-timeout
          - Authenticated registries: configuration/authenticated-registries.md
          - Vulnerability database persistence: configuration/vulnerability-database-persistence.md
          - Private registries:
              - AWS ECR: configuration/private-registries/ecr.md
              - Azure ACR: configuration/private-registries/acr.md
      - "üîå Plugins":
          - Overview: plugins/index.md
          - Misconfiguration:
            - Marvin: plugins/marvin.md
            - Popeye: plugins/popeye.md
          - Vulnerability:
            - Trivy: plugins/trivy.md
      - "üîÑ Migrating to 0.8": getting-started/installation/#migrating-to-08
#      - "üîê Data privacy": data-privacy.md
      - "üìä Zora Dashboard": dashboard.md
#      - "üóÉÔ∏è Troubleshooting": troubleshooting.md
      - "‚ùì FAQ": faq.md
  - Helm Chart:
      - Zora Helm Chart: helm-chart.md
