{{- if .Values.ui.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "snitch.uiServiceAccountName" . }}
  labels:
    {{- include "snitch.labels" . | nindent 4 }}
  {{- with .Values.ui.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
